In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [2]:
# In my local Machine, I ah only taking fewer rows for faster local training and development
# In Kaggle comment-out below line
train_df_org = pd.read_csv('kaggle/input/digit-recognizer/train.csv',  nrows=1000)
test_df_org = pd.read_csv('kaggle/input/digit-recognizer/test.csv',  nrows=1000)

# Instead, uncomment the below one, where the whole dataset is taken for traiing
# train_df_org = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')
# test_df_org = pd.read_csv('/kaggle/input/digit-recognizer/test.csv')

print("train_df_org shape ", train_df_org.shape) #  (1000, 785)
print("test_df_org shape ", test_df_org.shape)

train_df_org.head()

train_df_org shape  (1000, 785)
test_df_org shape  (1000, 784)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# In test df there should not be any label column.
# lets see it.
test_df_org.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In below the labels variable contains the labels and then from the 'train_df_org' (which contains all the actual image pixel) I will drop 'label' column

In [4]:
labels = train_df_org['label']
labels.shape

(1000,)

In [5]:
train_df_for_pca = train_df_org.drop(['label'], axis=1)
train_df_for_pca.shape

AttributeError: 'NoneType' object has no attribute 'shape'

#### Step-A: Data-preprocessing: Standardizing the train dataframe
#### `(x - mean) / s.d`

In [ ]:
standardized_data = StandardScaler().fit_transform(train_df_for_pca)
print(standardized_data.shape)